package main

import (
	"fmt"
	"math/big"

	// "math/rand"
	"crypto/rand"
)

func main() {
	fmt.Println("Welcome to maths in Golang")

	// var numOne int = 5
	// var numTwo float64 = 45.5

	// fmt.Println("Addition of numOne and numTwo:", numOne + int(numTwo))

	//random number(math/rand)

	// rand.Seed(time.Now().UnixNano())
	// fmt.Println("The random number generated by math library is:", rand.Intn(5)) 

	//random number(crypto/rand)
	myRandNum, _ := rand.Int(rand.Reader, big.NewInt(5))
	fmt.Println("the random number genereated by crypto library is:", myRandNum)
}